name: CI-Pipeline

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - develop
      - 'release/*'
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [employeeManager, ticketsystem]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Dependencies
        working-directory: ./project/${{ matrix.app }}
        run: mvn dependency:resolve

      - name: Build with Maven
        working-directory: ./project/${{ matrix.app }}
        run: mvn clean compile

      - name: Run Unit Tests
        working-directory: ./project/${{ matrix.app }}
        run: mvn test
        env:
          MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.app }}-test-results
          path: ./project/${{ matrix.app }}/target/surefire-reports/