name: Multi-Module CI Pipeline

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - develop
      - 'release/*'
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up JDK 21
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Install Parent Dependencies
      - name: Install Parent Dependencies
        working-directory: ./project/ticket-system
        run: mvn dependency:resolve

      # Step 4: Build All Modules
      - name: Build All Modules
        working-directory: ./project/ticket-system
        run: mvn clean compile

      # Step 5: Run Unit Tests for All Modules
      - name: Run Unit Tests
        working-directory: ./project/ticket-system
        run: mvn test
        env:
          MAVEN_OPTS: "-Dmaven.test.failure.ignore=true"

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: project/ticket-system/**/target/surefire-reports/