name: Multi-Module CI Pipeline

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - develop
      - 'release/*'
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Parent Dependencies
        working-directory: ./project/ticket-system
        run: mvn dependency:resolve

      - name: Build All Modules
        working-directory: ./project/ticket-system
        run: mvn clean compile

      - name: Run Unit Tests
        working-directory: ./project/ticket-system
        run: mvn test
        env:
          MAVEN_OPTS: "-Dmaven.test.failure.ignore=false"

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: project/ticket-system/**/target/surefire-reports/

  performance-tests:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Performance Tests
        working-directory: ./project/ticket-system/ticketverwaltung
        run: |
          mvn test -Dtest=DatabasePerformanceTest
        env:
          MAVEN_OPTS: "-Dmaven.test.failure.ignore=false"

      - name: Archive Performance Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: performance-test-results
          path: project/ticket-system/**/target/surefire-reports/