name: Multi-Module CI Pipeline

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - develop
      - 'release/*'
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Parent Dependencies
        working-directory: ./project/ticket-system
        run: mvn dependency:resolve

      - name: Build All Modules
        working-directory: ./project/ticket-system
        run: mvn clean package

      - name: Run Unit Tests
        working-directory: ./project/ticket-system
        run: mvn test
        env:
          MAVEN_OPTS: "-Dmaven.test.failure.ignore=false"

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: project/ticket-system/**/target/surefire-reports/

  performance-tests:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Performance Tests
        working-directory: ./project/ticket-system/ticketverwaltung
        run: |
          echo "Running performance tests using Maven..."
          mvn test -Dtest=*PerformanceTest -Dsurefire.failIfNoSpecifiedTests=false
        env:
          MAVEN_OPTS: "-Dmaven.test.failure.ignore=false"

      - name: Archive Performance Test Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: performance-test-results
          path: project/ticket-system/**/target/surefire-reports/

  build-and-push-docker:
    runs-on: ubuntu-latest
    needs: performance-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build ticketverwaltung Module
        working-directory: ./project/ticket-system/ticketverwaltung
        run: mvn clean package

      - name: Debug ticketverwaltung Build Directory
        working-directory: ./project/ticket-system/ticketverwaltung
        run: ls -la target

      - name: Build and Push ticketverwaltung Image
        working-directory: ./project/ticket-system/ticketverwaltung
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ticketverwaltung:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/ticketverwaltung:latest

      - name: Build employeemanager Module
        working-directory: ./project/ticket-system/employeemanager
        run: mvn clean package

      - name: Debug employeemanager Build Directory
        working-directory: ./project/ticket-system/employeemanager
        run: ls -la target

      - name: Build and Push employeemanager Image
        working-directory: ./project/ticket-system/employeemanager
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/employeemanager:latest -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/employeemanager:latest
