version: "3.8"
services:
  ticketverwaltung:
    build:
      context: ./ticketverwaltung
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - h2db

  employeemanager:
    build:
      context: ./employeeManager
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - h2db

  h2db:
    image: oscarfonts/h2
    ports:
      - "9092:1521"
    environment:
      - H2_OPTIONS=-tcp -tcpAllowOthers -web
